version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo Entered the install phase on `date`
      - |
        echo Installing Rust
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none --profile minimal
        export PATH="/root/.cargo/bin:$PATH"
        pip3 install cargo-lambda
    finally:
      - |
        echo Changing all file times to 2010-01-01 00:00:00 \(arbitrary\) to avoid inducing changes in ZIP packages
        find . -not -path '*/.git/*' -exec touch -a -m -t"201001010000.00" {} \;
      - echo Exiting the install phase on `date`
  pre_build:
    on-failure: ABORT
    commands:
      - echo Entered the pre_build phase on `date`
      ##################
      # RUST PRE-BUILD #
      ##################
      - |
        RUST_LIB_PATH=./rust/libs
        RUST_LAMBDA_PATH=./rust/lambdas
        GRAPHQL_SCHEMA_FILE=./graphql/schema.gql
        mkdir -p $RUST_LIB_PATH 2>/dev/null
        mkdir -p $RUST_LAMBDA_PATH 2>/dev/null
      - |
        current_build_rust_version=$(cargo --version 2>/dev/null)
        echo "Rust version: $current_build_rust_version"
        if ! previous_build_rust_version=$(cat previous_build_rust_version 2>/dev/null) || [ "$previous_build_rust_version" != "$current_build_rust_version" ]; then
          echo "Rust version changed $previous_build_rust_version -> $current_build_rust_version, cleaning everything"
          cargo clean --locked
          echo "$current_build_rust_version" > previous_build_rust_version
        fi
      - |
        ##########################
        #    Bash Hash Tables    #
        ##########################
        declare -A PACKAGES_TO_CLEAN
        declare -A IMPACTED_PACKAGE_NAMES
        ##########################
        #        Functions       #
        ##########################
        # Function checking if any dependency of a crate will be cleaned
        will_dep_be_cleaned () {
          CRATE=$1
          for dep in $(cargo tree --locked --prefix none --package $CRATE | sed -r 's/^(\S+)\s+v(\S+).*$/\1@\2/' | sort -u); do
            dep_name=${dep%@*}
            if [[ ${IMPACTED_PACKAGE_NAMES[$dep_name]} -eq 1 ]] || [[ ${PACKAGES_TO_CLEAN[$dep_name]} -eq 1 ]]; then
              return 0
            fi
          done
          return 1
        }
        # Function checking if a local package need cleaning
        process_local_crate_cleaning () {
          LOCAL_CRATE_NAME=$1
          current_md5=$2
          if ! previous_md5=$(cat rust_target_md5sum/$LOCAL_CRATE_NAME 2>/dev/null) || [ "$previous_md5" != "$current_md5" ] ; then
            echo previous_md5=$previous_md5 current_md5=$current_md5 =\> Change detected for $LOCAL_CRATE_NAME, cleaning it and updating md5sum
            PACKAGES_TO_CLEAN+=([$LOCAL_CRATE_NAME]=1)
            echo $current_md5 > rust_target_md5sum/$LOCAL_CRATE_NAME
          elif will_dep_be_cleaned $LOCAL_CRATE_NAME ; then
            echo One of $LOCAL_CRATE_NAME dependencies will be cleaned, cleaning it
            PACKAGES_TO_CLEAN+=([$LOCAL_CRATE_NAME]=1)
          fi
        }
        # Function generating the current dependency tree
        dependencies_tree () {
          cargo tree --locked --prefix none --target all -f '{p} feats:{f}' | sed -r 's/^(\S+)\s+v(\S+).* feats:(\S*).*$/\1@\2#\3/' | sort -u
        }
        # Function generating the list of packages that depends on a package
        invert_dependencies_tree () {
          cargo tree --locked --prefix none --target all --invert $1 | sed -r 's/^(\S+)\s+v(\S+).*$/\1@\2/' | sort -u
        }
        # Function systematicly cleaning the files related to a package in the target directory
        manual_clean_package () {
          package_name=$1
          echo "Manually cleaning $package_name"
          find target/ -type d -regextype posix-egrep -regex ".+./\.fingerprint/${package_name}-[a-f0-9]{16}"
          for fg_folder in $(find target/ -type d -regextype posix-egrep -regex ".+./\.fingerprint/${package_name}-[a-f0-9]{16}" -exec basename {} \;) ; do
            fg=${fg_folder: -16}
            # Clean build folders if they exist
            find target/ -type d -regextype posix-egrep -regex ".+/build/${fg_folder}"
            find target/ -type d -regextype posix-egrep -regex ".+/build/${fg_folder}" -exec rm -r {} +
            # Clean deps files if they exist
            dep_name=$(tr '-' '_' <<< "$package_name")
            dep_name="${dep_name}-${fg}"
            find target/ -type f -regextype posix-egrep -regex ".+/deps/(lib)?${dep_name}\..+"
            find target/ -type f -regextype posix-egrep -regex ".+/deps/(lib)?${dep_name}\..+" -exec rm {} +
          done
          find target/ -type d -regextype posix-egrep -regex ".+./\.fingerprint/${package_name}-[a-f0-9]{16}" -exec rm -r {} +
        }
        ##########################
        #     Cache cleaning     #
        ##########################
        if [ -f previous_dependencies_tree ] ; then
          echo Cleaning cached target directory
          declare -A CURRENT_PACKAGES
          echo Building current dependencies tree...
          for p in $(dependencies_tree) ; do
            CURRENT_PACKAGES+=([$p]=1)
          done
          echo Finding all packages that are no longer needed or changed...
          for p in $(cat previous_dependencies_tree) ; do
            if ! [[ ${CURRENT_PACKAGES[$p]} -eq 1 ]]; then
              package_id=${p%#*}
              package_name=${p%@*}
              if cargo pkgid $package_id 2>/dev/null >/dev/null ; then
                echo "Cleaning $package_id and packages depending on it"
                for ptc in $(invert_dependencies_tree $package_id); do
                  ptc_name=${ptc%@*}
                  manual_clean_package "$ptc_name"
                  IMPACTED_PACKAGE_NAMES+=([$ptc_name]=1)
                done
              else
                manual_clean_package "$package_name"
                IMPACTED_PACKAGE_NAMES+=([$package_name]=1)
              fi
            fi
          done
        else
          echo No cached target directory
        fi
        ##########################
        #  Local Crates cleaning #
        ##########################
        if ! [ -d rust_target_md5sum ] ; then mkdir rust_target_md5sum ; fi
        echo Selectively clean-up LIB artifacts if code has changed
        for LIB in $(ls $RUST_LIB_PATH) ; do
          echo Control MD5 for $RUST_LIB_PATH/$LIB \($CRATE_ID\)
          cd $RUST_LIB_PATH/$LIB
          current_md5=$(find . | sort | zip -@ - | md5sum | cut -f1 -d" ")
          cd $CODEBUILD_SRC_DIR
          process_local_crate_cleaning "$LIB" "$current_md5"
        done
        echo Selectively clean-up LAMBDA artifacts if code has changed
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Control MD5 for $RUST_LAMBDA_PATH/$LAMBDA \($CRATE_ID\)
          cd $RUST_LAMBDA_PATH/$LAMBDA
          current_md5=$(find . | sort | zip -@ - | md5sum | cut -f1 -d" ")
          cd $CODEBUILD_SRC_DIR
          process_local_crate_cleaning "$LAMBDA" "$current_md5"
        done
        # This is an AppSync project
        # We need to verify if the schema.gql file has changed because
        # the lambda-appsync crate is using it to generate all the boiler-plate
        # of the Lambdas
        current_gql_md5=$(md5sum $GRAPHQL_SCHEMA_FILE | cut -f1 -d" ")
        if ! previous_gql_md5=$(cat rust_target_md5sum/gql_md5 2>/dev/null) || [ "$previous_gql_md5" != "$current_gql_md5" ] ; then
          echo previous_gql_md5=$previous_gql_md5 current_gql_md5=$current_gql_md5 =\> Clean all lambda using the lambda_appsync crate
          for LIB in $(ls $RUST_LIB_PATH) ; do
            echo Control lambda_appsync crate usage for $RUST_LIB_PATH/$LIB
            if grep -r lambda_appsync $RUST_LIB_PATH/$LIB/ ; then
              PACKAGES_TO_CLEAN+=([$LIB]=1)
            fi
          done
          for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
            echo Control lambda_appsync crate usage for $RUST_LAMBDA_PATH/$LAMBDA
            if grep -r lambda_appsync $RUST_LAMBDA_PATH/$LAMBDA/ ; then
              PACKAGES_TO_CLEAN+=([$LAMBDA]=1)
            fi
          done
          echo $current_gql_md5 > rust_target_md5sum/gql_md5
        fi
        echo Cleaning ${#PACKAGES_TO_CLEAN[@]} packages...
        for package in ${!PACKAGES_TO_CLEAN[@]}; do
          echo Cleaning $package
          cargo clean --locked --target aarch64-unknown-linux-gnu --release --package $package
        done
        ##########################
        #    Dependencies Tree   #
        ##########################
        echo Saving current dependency tree as previous_dependencies_tree
        dependencies_tree > previous_dependencies_tree
      ####################
      # PYTHON PRE-BUILD #
      ####################
      - |
        PYTHON_LAYERS_PATH=./python/layers
        PYTHON_LAMBDA_PATH=./python/lambdas
    finally:
      - echo Exiting the pre_build phase on `date`
  build:
    on-failure: ABORT
    commands:
      - echo Entered the build phase on `date`
      ##############
      # RUST BUILD #
      ##############
      - |
        echo Composing the release build command...
        CMD="cargo lambda build --locked --release --arm64"
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Will build $LAMBDA
          CMD="$CMD --package $LAMBDA"
        done
        echo $CMD
        eval $CMD
      - |
        echo Packaging lambdas...
        for LAMBDA in $(ls $RUST_LAMBDA_PATH) ; do
          echo Preping: $LAMBDA
          # Remove all content
          rm -rf $RUST_LAMBDA_PATH/$LAMBDA/*
          # Move the compiled binary into the Lambda folder
          mv ./target/lambda/$LAMBDA/bootstrap $RUST_LAMBDA_PATH/$LAMBDA/bootstrap
        done
      ################
      # PYTHON BUILD #
      ################
      - |
        echo Installing dependencies for the Python lambdas
        for LAMBDA in $(ls $PYTHON_LAMBDA_PATH) ; do
          if [ -f "$PYTHON_LAMBDA_PATH/$LAMBDA/requirements.txt" ]; then
            echo Installing dependencies for Python lambda: $LAMBDA
            pip install -r $PYTHON_LAMBDA_PATH/$LAMBDA/requirements.txt -t $PYTHON_LAMBDA_PATH/$LAMBDA
            rm $PYTHON_LAMBDA_PATH/$LAMBDA/requirements.txt
          fi
        done
    finally:
      - |
        echo Changing all file times to 2010-01-01 00:00:00 \(arbitrary\) to avoid inducing changes in ZIP packages
        find . -not -path '*/.git/*' -exec touch -a -m -t"201001010000.00" {} \;
      - echo Exiting the build phase on `date`
  post_build:
    commands:
      - echo Entered the post_build phase on `date`
      - |
        echo Packaging the sub-templates file references...
        for SUBTEMPLATE in $(ls ./templates) ; do
          echo Packaging sub-template $SUBTEMPLATE
          mv ./templates/$SUBTEMPLATE ./templates/$SUBTEMPLATE.bak
          aws cloudformation package --template-file ./templates/$SUBTEMPLATE.bak --s3-bucket $ARTIFACT_BUCKET --s3-prefix templates --output-template-file ./templates/$SUBTEMPLATE
        done
      - |
        echo Packaging the root-template file references...
        mv root-template.yml root-template.yml.bak
        aws cloudformation package --template-file root-template.yml.bak --s3-bucket $ARTIFACT_BUCKET --s3-prefix templates --output-template-file root-template.yml
    finally:
      - echo Exiting the post_build phase on `date`
artifacts:
  secondary-artifacts:
    Infra:
      base-directory: .
      files:
        - root-template.yml
    Website:
      base-directory: website
      files:
        - "**/*"
cache:
  paths:
    - target/**/* # Rust workspace target directory
    - rust_target_md5sum/**/* # Where we store md5sum for code
    - previous_dependencies_tree # The last seen dependencies tree
    - previous_build_rust_version # The last seen Rust toolchain version
