// dynamodb-facade is a project-specific wrapper around the AWS DynamoDB SDK.
// It provides trait-based abstractions (DynamoDBItem, DynamoDBItemOp, etc.)
// for type-safe single-table DynamoDB operations.
use dynamodb_facade::{
    Condition, DynamoDBError, DynamoDBItem, DynamoDBItemBatchOp, DynamoDBItemOp,
    DynamoDBItemTransactOp, KeyId, ScanRequest, Update, batch_delete, dynamodb_batch_write,
};
// AppsyncError: the error type returned to AppSync clients.
// ID: newtype wrapper for GraphQL ID scalars (UUID-based).
// appsync_operation: macro that registers a function as a handler for a specific GraphQL operation.
use lambda_appsync::{AppsyncError, ID, appsync_operation};

// dynamodb(): the instrumented client accessor generated by make_lambda_runtime! in main.rs.
// game_engine::*: all game domain types generated from the GraphQL schema.
// trace_appsync_error!: macro from error_utils.rs that creates errors and sets X-Ray error status.
use crate::{
    dynamodb,
    dynamodb_table::{ItemType, MonoTable},
    error_utils::{facade2appsync, internal_server_error},
    game_engine::*,
    trace_appsync_error,
};

// #[tracing::instrument(ret)] auto-creates a tracing span for this function call and logs the return value.
// #[appsync_operation(query(gameState))] registers this as the handler for the `gameState` GraphQL query.
// The make_handlers! macro routes Query.gameState events here.
#[tracing::instrument(ret)]
#[appsync_operation(query(gameState))]
pub async fn game_state() -> Result<GameState, AppsyncError> {
    // Full table scan: retrieves ALL items. In single-table design, different entity types
    // are distinguished by their _TYPE attribute (read via item_type()).
    let items = ScanRequest::<MonoTable>::new(dynamodb())
        .all()
        .await
        .map_err(facade2appsync)?;

    let mut game_state = GameState::default();
    for item in items {
        // Pattern match on the entity type to deserialize each item into its proper Rust struct.
        // from_item() is provided by the DynamoDBItem trait from dynamodb-facade.
        match item.attribute::<ItemType>() {
            Some(Player::TYPE) => game_state.players.push(Player::from_item(item)),
            Some(GameStatus::TYPE) => game_state.game_status = GameStatus::from_item(item),
            Some(GameCounts::TYPE) => {
                let game_counts = GameCounts::from_item(item);
                // into() calls From<GameCounts> implementations that convert
                // internal game counts into the GraphQL-facing types
                game_state.job_fees = game_counts.into();
                game_state.yak_counts = game_counts.into();
            }
            // log and ignore unrecognized types (forward compatibility)
            Some(unknown_type) => {
                tracing::debug!(message = "Skipping item with unknown type", ?unknown_type)
            }
            None => tracing::debug!(message = "Skipping item without type"),
        }
    }
    Ok(game_state)
}

#[tracing::instrument(ret)]
#[appsync_operation(mutation(startGame))]
pub async fn start_game() -> Result<GameUpdate, AppsyncError> {
    // tokio::try_join! runs multiple async operations CONCURRENTLY (not sequentially)
    // and returns when all complete or any fails.
    let (game_counts, game_status) = tokio::try_join!(
        async {
            // KeyId::NONE: GameCounts is a singleton item (no primary key needed)
            let game_count = GameCounts::get(dynamodb(), KeyId::NONE)
                .await?
                .map(|game_count| game_count.reset())
                .unwrap_or_else(|| GameCounts::with_player_count(0));
            game_count.put(dynamodb()).await?;
            Ok(game_count)
        },
        // Conditional put: only transitions to Started if current status is Reset or absent.
        // Prevents invalid state transitions. Uses DynamoDB conditional expressions.
        GameStatus::Started.put_if_current_status_compatible(dynamodb())
    )
    .map_err(facade2appsync)?;

    // Builder pattern: constructs a GameUpdate from the status, marks it as sampled
    // (triggers subscription delivery to players), and derives yak counts/fees from game counts.
    Ok(GameUpdate::from(game_status)
        .sampled()
        .with_game_counts_derived(game_counts))
}

#[tracing::instrument(ret)]
#[appsync_operation(mutation(stopGame))]
pub async fn stop_game() -> Result<GameUpdate, AppsyncError> {
    let (game_counts, game_status) = tokio::try_join!(
        GameCounts::with_updated_desired_yak_count(dynamodb(), 0),
        GameStatus::Stopped.put_if_current_status_compatible(dynamodb())
    )
    .map_err(facade2appsync)?;
    Ok(GameUpdate::from(game_status)
        .sampled()
        .with_game_counts_derived(game_counts))
}

#[tracing::instrument(ret)]
#[appsync_operation(mutation(resetGame))]
pub async fn reset_game() -> Result<GameUpdate, AppsyncError> {
    // Start by setting the Reset state so players can no longer interact with the game
    let game_status = GameStatus::Reset
        .put_if_current_status_compatible(dynamodb())
        .await
        .map_err(facade2appsync)?;
    let mut game_update = GameUpdate::from(game_status).sampled();

    let items = ScanRequest::<MonoTable>::new(dynamodb())
        .all()
        .await
        .map_err(facade2appsync)?;

    let batch_write_requests = items
        .into_iter()
        .filter_map(|item| match item.attribute::<ItemType>() {
            Some(Player::TYPE) => Some(PlayerWithSecret::from_item(item).reset().batch_put()),
            Some(Yak::TYPE) => Some(batch_delete(item.into_key_only())),
            Some(GameCounts::TYPE) => {
                let game_counts = GameCounts::from_item(item).reset();
                game_update.job_fees = Some(game_counts.into());
                game_update.yak_counts = Some(game_counts.into());
                Some(game_counts.batch_put())
            }
            Some(GameStatus::TYPE) => None,
            Some(unknown_type) => {
                tracing::debug!(message = "Skipping item with unknown type", ?unknown_type);
                None
            }
            None => {
                tracing::debug!(message = "Skipping item without type");
                None
            }
        })
        .collect::<Vec<_>>();
    dynamodb_batch_write::<MonoTable>(dynamodb(), batch_write_requests)
        .await
        .map_err(facade2appsync)?;

    Ok(game_update)
}

// fields(%player_id): records player_id as a Display-formatted span field (searchable in X-Ray).
#[tracing::instrument(ret, fields(%player_id))]
#[appsync_operation(mutation(removePlayer))]
pub async fn remove_player(player_id: ID) -> Result<Player, AppsyncError> {
    let player = Player::get(dynamodb(), KeyId::pk(player_id))
        .await
        .map_err(facade2appsync)?
        // ok_or_else converts Option<Player> to Result. trace_appsync_error! also sets X-Ray error status.
        .ok_or_else(|| trace_appsync_error!("PlayerNotFound", "Player does not exist"))?;

    // DynamoDB Transaction: atomically deletes the player AND decrements the player count.
    // Both succeed or both fail — prevents inconsistency.
    dynamodb()
        .transact_write_items()
        .transact_items(
            Player::transact_delete_by_id(KeyId::pk(player_id))
                // Condition: only delete if the item exists (prevents double-deletion)
                .exists()
                .build(),
        )
        .transact_items(
            // Atomically decrement the counter with a guard preventing it from going negative
            GameCounts::transact_update_by_id(KeyId::NONE, Update::decrement("player_count", 1))
                .condition(GameCounts::exists() & Condition::gt("player_count", 0))
                .build(),
        )
        .send()
        .await?;

    Ok(player)
}

// skip(secret): excludes the secret from trace logs (security).
// fields(player_id): declares a span field that will be filled later with .record().
#[tracing::instrument(ret, skip(secret), fields(player_id, player_name=%name))]
#[appsync_operation(mutation(registerNewPlayer))]
pub async fn register_new_player(name: String, secret: String) -> Result<GameUpdate, AppsyncError> {
    let new_player_with_secret = PlayerWithSecret::new(name, secret);
    // Conditional put: only creates the player if no item with this PK/SK exists (UUID collision protection)
    new_player_with_secret
        .put(dynamodb())
        .condition(PlayerWithSecret::not_exists())
        .await
        .map_err(facade2appsync)?;

    // Async closure used as a rollback function: if incrementing the game count fails,
    // this deletes the just-created player to maintain consistency.
    let try_rollback_player_creation = async |error| {
        let _ = new_player_with_secret
            .delete(dynamodb())
            .await
            // Warn and supress the error
            .map_err(|error| {
                tracing::warn!(message = "Could not rollback player creation", ?error);
            })
            .ok();
        internal_server_error(error)
    };
    // Local `use` import (Rust idiom): brings Error into scope as DynamoError for pattern matching
    use dynamodb_facade::Error;

    // Local helper function defined inside another function (Rust allows this)
    async fn increment_gamecount() -> Result<GameCounts, Error> {
        GameCounts::update_by_id(
            dynamodb(),
            KeyId::NONE,
            Update::increment("player_count", 1),
        )
        .exists()
        .await
    }

    // Multi-level error recovery for concurrent player registrations:
    // 1. Try incrementing player_count
    // 2. If item doesn't exist (first player), try creating it
    // 3. On race condition (another player created it simultaneously), retry increment
    // 4. On any other error, rollback the player creation
    let game_counts = match increment_gamecount().await {
        Ok(game_counts) => game_counts,
        // This is the first time we use the GameCount, need to create it
        Err(error1) => {
            if let Some(DynamoDBError::ConditionalCheckFailedException(_)) =
                error1.as_dynamodb_error()
            {
                let game_counts = GameCounts::with_player_count(1);
                match game_counts.put(dynamodb()).not_exists().await {
                    Ok(_) => game_counts,
                    Err(error2) => {
                        if let Some(DynamoDBError::ConditionalCheckFailedException(_)) =
                            error2.as_dynamodb_error()
                        {
                            // Race condition, multiple player attempted to create the GameCount
                            // Just retry the regular creation
                            match increment_gamecount().await {
                                Ok(game_counts) => game_counts,
                                Err(error3) => {
                                    // Ok this time I'm out of option
                                    tracing::error!(
                                        message = "Could not create GameCounts",
                                        ?error3
                                    );
                                    return Err(try_rollback_player_creation(error3).await);
                                }
                            }
                        } else {
                            tracing::error!(message = "Could not create GameCounts", ?error2);
                            return Err(try_rollback_player_creation(error2).await);
                        }
                    }
                }
            } else {
                tracing::error!(message = "Could not increment GameCounts", ?error1);
                return Err(try_rollback_player_creation(error1).await);
            }
        }
    };
    let new_player = new_player_with_secret.into_player();
    // Fill the span field declared earlier (player_id was unknown until the player was created)
    tracing::Span::current().record("player_id", new_player.id.to_string());

    Ok(GameUpdate::from(new_player)
        .sampled()
        .with_game_counts_derived(game_counts))
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name=%new_name))]
#[appsync_operation(mutation(updatePlayerName))]
pub async fn update_player_name(
    player_id: ID,
    secret: String,
    new_name: String,
) -> Result<GameUpdate, AppsyncError> {
    Ok(GameUpdate::from(
        Player::update_with_secret_check(
            dynamodb(),
            KeyId::pk(player_id),
            Update::set("name", new_name),
            secret,
        )
        .await
        .map_err(facade2appsync)?,
    )
    .sampled())
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, yak_id, job))]
#[appsync_operation(mutation(buyBabyYak))]
pub async fn buy_baby_yak(player_id: ID, secret: String) -> Result<GameUpdate, AppsyncError> {
    buy_yak(player_id, secret, None, Job::Breeder).await
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, %yak_id, job))]
#[appsync_operation(mutation(sellGrownYak))]
pub async fn sell_grown_yak(
    player_id: ID,
    secret: String,
    yak_id: ID,
) -> Result<GameUpdate, AppsyncError> {
    sell_yak(
        player_id,
        secret,
        yak_id,
        Job::Breeder,
        Some(WaitingPlace::Warehouse),
    )
    .await
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, yak_id, job))]
#[appsync_operation(mutation(buyGrownYak))]
pub async fn buy_grown_yak(player_id: ID, secret: String) -> Result<GameUpdate, AppsyncError> {
    buy_yak(
        player_id,
        secret,
        Some(WaitingPlace::Warehouse),
        Job::Driver,
    )
    .await
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, %yak_id, job))]
#[appsync_operation(mutation(sellUnshearedYak))]
pub async fn sell_unsheared_yak(
    player_id: ID,
    secret: String,
    yak_id: ID,
) -> Result<GameUpdate, AppsyncError> {
    sell_yak(
        player_id,
        secret,
        yak_id,
        Job::Driver,
        Some(WaitingPlace::ShearingShed),
    )
    .await
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, yak_id, job))]
#[appsync_operation(mutation(buyUnshearedYak))]
pub async fn buy_unsheared_yak(player_id: ID, secret: String) -> Result<GameUpdate, AppsyncError> {
    buy_yak(
        player_id,
        secret,
        Some(WaitingPlace::ShearingShed),
        Job::Shearer,
    )
    .await
}

#[tracing::instrument(ret, skip(secret), fields(%player_id, player_name, %yak_id, job))]
#[appsync_operation(mutation(sellShearedYak))]
pub async fn sell_sheared_yak(
    player_id: ID,
    secret: String,
    yak_id: ID,
) -> Result<GameUpdate, AppsyncError> {
    sell_yak(player_id, secret, yak_id, Job::Shearer, None).await
}

pub async fn buy_yak(
    player_id: ID,
    secret: String,
    from_place: Option<WaitingPlace>,
    for_job: Job,
) -> Result<GameUpdate, AppsyncError> {
    let current_span = tracing::Span::current();
    current_span.record("job", for_job.to_string());

    let (yak, player, game_status, game_counts) = tokio::try_join!(
        async {
            match from_place {
                Some(from_place) => {
                    Some(WaitingYak::get_random_waiting(dynamodb(), from_place).await).transpose()
                }
                None => Ok(None),
            }
        },
        Player::get(dynamodb(), KeyId::pk(player_id)),
        GameStatus::get(dynamodb(), KeyId::NONE),
        GameCounts::get(dynamodb(), KeyId::NONE)
    )
    .map_err(internal_server_error)?;

    let mut player =
        player.ok_or_else(|| trace_appsync_error!("PlayerNotFound", "Player does not exist"))?;
    current_span.record("player_name", &player.name);

    // A player that already have a job should never be able to buy a Yak
    if player.assignment.is_some() {
        return Err(trace_appsync_error!(
            "InvalidPlayerStatus",
            "You already have another job! That should not happen 😅",
        ));
    }

    // Open a transaction
    let transaction = dynamodb().transact_write_items();

    let (transaction, yak) = if let Some(from_place) = from_place {
        // Buying a Yak is only possible if the game is not RESET
        if matches!(game_status, Some(GameStatus::Reset)) {
            return Err(trace_appsync_error!(
                "InvalidGameStatus",
                "The game is reset"
            ));
        }
        let waiting_yak = yak.unwrap().ok_or_else(|| {
            trace_appsync_error!("NoMoreYak", format!("No more yaks in the {from_place}"))
        })?;
        // Transactionally move the Yak in DynamoDB
        // Delete it from its old location
        let transaction =
            transaction.transact_items(waiting_yak.transact_delete().exists().build());

        (transaction, waiting_yak.into())
    } else {
        // Creating a Yak is only possible if the game is started
        if !matches!(game_status, Some(GameStatus::Started)) {
            return Err(trace_appsync_error!(
                "InvalidGameStatus",
                "The game is not started",
            ));
        }
        (transaction, Yak::new())
    };

    let game_status = game_status.ok_or_else(|| internal_server_error("Missing GameStatus"))?;
    let game_counts = game_counts.ok_or_else(|| internal_server_error("Missing GameCounts"))?;
    // Verify the buy if possible
    if let Some(from_place) = from_place {
        if game_counts[from_place] == 0 {
            return Err(trace_appsync_error!(
                "NoMoreYak",
                format!("No more yak in the {from_place}")
            ));
        }
    } else if game_counts.total_yaks() >= game_counts.desired_yak_count() {
        return Err(trace_appsync_error!(
            "NoMoreYak",
            "No more yak in the nursery! Wait a little...",
        ));
    }

    // Mut the player object with the new infos
    current_span.record("yak_id", yak.id.to_string());
    player.start_new_assignment(for_job, yak, game_counts.job_fees());

    // Get a transaction
    let transaction =
        transaction.transact_items(player.transact_start_assignment_with_secret_check(secret));

    // Execute the transaction
    if let Err(e) = transaction.send().await {
        use aws_sdk_dynamodb::operation::transact_write_items::TransactWriteItemsError;
        let error = e.into_service_error();
        // If the Error is a ConditionalCheckFail for the deletion part of the Yak move
        // then it means a race condition happened between 2 players trying to buy the same yak.
        // It should happen fairly often, so we return a nicer message.
        return Err(
            if let Some(from_place) = from_place
                && let TransactWriteItemsError::TransactionCanceledException(
                    transaction_canceled_exception,
                ) = &error
            {
                match transaction_canceled_exception.cancellation_reasons()[0].code() {
                    Some("ConditionalCheckFailed") => trace_appsync_error!(
                        "NoMoreYak",
                        format!("No more yak in the {from_place}")
                    ),
                    Some("TransactionConflict") => trace_appsync_error!(
                        "YakAlreadyTaken",
                        format!("Somebody else got the yak for {from_place}")
                    ),
                    _ => internal_server_error(error),
                }
            } else {
                internal_server_error(error)
            },
        );
    }

    // Update the GameCounts object
    // INFO: This is not part of the transaction because this particular
    // item is common to all players. So with 250 concurrent players,
    // putting it in the transaction would create *A LOT* of TransactionCanceledException
    let game_counts = game_counts
        .update_move_yak_with_sample_tracking(
            dynamodb(),
            from_place.map(GameCountIndex::WaitingPlace),
            Some(GameCountIndex::Job(for_job)),
        )
        .await
        .map_err(facade2appsync)?;

    Ok(GameUpdate::from(player)
        .with_game_status(game_status)
        .with_game_counts_derived(game_counts))
}

pub async fn sell_yak(
    player_id: ID,
    secret: String,
    yak_id: ID,
    from_job: Job,
    to_place: Option<WaitingPlace>,
) -> Result<GameUpdate, AppsyncError> {
    let current_span = tracing::Span::current();
    current_span.record("job", from_job.to_string());

    let (player, game_counts) = tokio::try_join!(
        Player::get(dynamodb(), KeyId::pk(player_id)),
        GameCounts::get(dynamodb(), KeyId::NONE),
    )
    .map_err(internal_server_error)?;

    let mut player =
        player.ok_or_else(|| trace_appsync_error!("PlayerNotFound", "Player does not exist"))?;
    current_span.record("player_name", &player.name);

    let game_counts = game_counts.ok_or_else(|| internal_server_error("Missing GameCounts"))?;

    // A player that do not have a job or not the corerct one should never be able to sell a Yak
    match &player.assignment {
        None => {
            return Err(trace_appsync_error!(
                "InvalidPlayerStatus",
                "You don't have a job! How would you get a Yak anyway? That should not happen 😅",
            ));
        }
        Some(assignment) => {
            if assignment.job != from_job {
                return Err(trace_appsync_error!(
                    "InvalidPlayerStatus",
                    format!("You are a {}, not a {from_job}!", assignment.job),
                ));
            }
            if assignment.yak_id() != yak_id {
                return Err(trace_appsync_error!(
                    "YakNotFound",
                    "The Yak does not exist"
                ));
            }
        }
    }

    // Get a transaction
    let transaction = dynamodb().transact_write_items();

    // Create the transaction
    let transaction =
        transaction.transact_items(player.transact_finish_assignment_with_secret_check(secret));

    // Mut the player object with the new infos
    let yak = player.finish_assignment();
    let waiting_yak = to_place.map(|to_place| WaitingYak::new(yak, to_place));

    let transaction = if let Some(waiting_yak) = waiting_yak {
        // Add it in the new location
        transaction.transact_items(waiting_yak.transact_put().not_exists().build())
    } else {
        // No destination place, the Yak is sheared
        // Don't perform another operation (just delete the yak in other words)
        transaction
    };

    // Execute the transaction
    transaction.send().await.map_err(internal_server_error)?;

    // Update the GameCounts object
    // INFO: This is not part of the transaction because this particular
    // item is common to all players. Meaning putting it in the transaction
    // would create *A LOT* of TransactionCanceledException
    let game_counts = game_counts
        .update_move_yak_with_sample_tracking(
            dynamodb(),
            Some(GameCountIndex::Job(from_job)),
            to_place.map(GameCountIndex::WaitingPlace),
        )
        .await
        .map_err(facade2appsync)?;

    Ok(GameUpdate::from(player).with_game_counts_derived(game_counts))
}
