// This Lambda is instrumented with `awssdk-instrumentation(otel)`.
// The handler code is IDENTICAL to no-instrumentation-demo — instrumentation is transparent.
// The only difference is the bottom of the file: `make_lambda_runtime!` replaces ~30 lines
// of manual boilerplate (tracing subscriber, SDK config, client init, Lambda runtime setup).

use aws_lambda_events::{
    event::{sns::SnsMessage, sqs::SqsBatchResponse},
    sqs::SqsEventObj,
};
use dynamodb_facade::AttributeValue;
// awssdk-instrumentation re-exports lambda_runtime so you use the exact same version
use awssdk_instrumentation::{
    lambda::{LambdaError, LambdaEvent},
    opentelemetry::{
        Context,
        trace::{FutureExt, TraceContextExt, Tracer},
    },
};

async fn handler(event: LambdaEvent<serde_json::Value>) -> Result<SqsBatchResponse, LambdaError> {
    // Get a tracer
    let span = global::tracer("").start("handler");

    async {
        println!("{}", event.payload.to_string());

        let sqs_payload: SqsEventObj<SnsMessage> =
            serde_json::from_value(event.payload).expect("should be sqs event payload");

        let mut response = SqsBatchResponse::default();

        for record in sqs_payload.records {
            let sns_message_id = record.body.message_id;
            tracing::info!(%sns_message_id, "Processing SNS message");
            let table_name = std::env::var("TABLE_NAME").expect("TABLE_NAME must be set");
            let lambda_name = std::env::var("LAMBDA_NAME").expect("LAMBDA_NAME must be set");
            // dynamodb() is generated by the macro below.
            // The client has an OTel interceptor pre-attached, so all DynamoDB calls
            // automatically appear as spans in X-Ray traces with semantic-convention attributes.
            match dynamodb()
                .put_item()
                .table_name(table_name)
                .item("PK", AttributeValue::S(sns_message_id))
                .item("SK", AttributeValue::S(lambda_name))
                .send()
                .await
            {
                Ok(_) => {}
                Err(error) => {
                    tracing::error!(%error, "Failed to process message");
                    if let Some(sqs_message_id) = record.message_id {
                        response.add_failure(sqs_message_id);
                    }
                }
            }
        }
        Ok(response)
    }
    .with_context(Context::current_with_span(span))
    .await
}

// Because the traing-backend feature is enabled, we need to explicitely
// write the telemetry_init() function without tracing wiring.
use awssdk_instrumentation::{
    init::default_tracer_provider,
    opentelemetry::global,
    opentelemetry_sdk::trace::SdkTracerProvider,
    tracing_subscriber::{self, util::SubscriberInitExt},
};
// This is the default_telemetry_init() function as it would be with only the otel-backend feature enabled
pub fn otel_only_telemetry_init() -> SdkTracerProvider {
    let tracer_provider = default_tracer_provider();
    global::set_tracer_provider(tracer_provider.clone());
    tracing_subscriber::registry().init();
    tracer_provider
}

// This single macro replaces ALL of the manual boilerplate from no-instrumentation-demo:
// - Generates #[tokio::main] async fn main()
// - Initializes OTel tracer provider with X-Ray exporter and environment resource detection
// - Sets up tracing-subscriber with JSON console layer + OTel bridge layer
// - Loads AWS SDK config, creates an instrumented DynamoDB client with OTel interceptor
// - Wraps the Lambda runtime with the OTel Tower layer (per-invocation spans, context propagation)
// - `trigger = OTelFaasTrigger::PubSub` sets the faas.trigger OTel attribute (this Lambda
//   is triggered by SNS/SQS, not HTTP)
//
// See: https://docs.rs/awssdk-instrumentation/latest/awssdk_instrumentation/macro.make_lambda_runtime.html
use awssdk_instrumentation::{
    interceptor::otel::OtelInterceptor,
    lambda::{OTelFaasTrigger, layer::OtelInstrumentor},
};
awssdk_instrumentation::make_lambda_runtime!(
    handler,
    telemetry_init = otel_only_telemetry_init,
    lambda_layer_instrumentor = OtelInstrumentor,
    trigger = OTelFaasTrigger::PubSub,
    dynamodb() -> dynamodb_facade::Client,
    sdk_client_interceptor = OtelInterceptor::new()
);
