// This Lambda is instrumented with `awssdk-instrumentation`.
// The handler code is IDENTICAL to no-instrumentation-demo — instrumentation is transparent.
// The only difference is the bottom of the file: `make_lambda_runtime!` replaces ~30 lines
// of manual boilerplate (tracing subscriber, SDK config, client init, Lambda runtime setup).

use aws_lambda_events::{
    event::{sns::SnsMessage, sqs::SqsBatchResponse},
    sqs::SqsEventObj,
};
use dynamodb_facade::AttributeValue;
// awssdk-instrumentation re-exports lambda_runtime so you use the exact same version
use awssdk_instrumentation::lambda::{LambdaError, LambdaEvent, OTelFaasTrigger};

#[tracing::instrument(skip_all)]
async fn handler(event: LambdaEvent<serde_json::Value>) -> Result<SqsBatchResponse, LambdaError> {
    println!("{}", event.payload.to_string());

    let sqs_payload: SqsEventObj<SnsMessage> =
        serde_json::from_value(event.payload).expect("should be sqs event payload");

    let mut response = SqsBatchResponse::default();

    for record in sqs_payload.records {
        let sns_message_id = record.body.message_id;
        tracing::info!(%sns_message_id, "Processing SNS message");
        let table_name = std::env::var("TABLE_NAME").expect("TABLE_NAME must be set");
        let lambda_name = std::env::var("LAMBDA_NAME").expect("LAMBDA_NAME must be set");
        // dynamodb() is generated by the macro below.
        // The client has an OTel interceptor pre-attached, so all DynamoDB calls
        // automatically appear as spans in X-Ray traces with semantic-convention attributes.
        match dynamodb()
            .put_item()
            .table_name(table_name)
            .item("PK", AttributeValue::S(sns_message_id))
            .item("SK", AttributeValue::S(lambda_name))
            .send()
            .await
        {
            Ok(_) => {}
            Err(error) => {
                tracing::error!(%error, "Failed to process message");
                if let Some(sqs_message_id) = record.message_id {
                    response.add_failure(sqs_message_id);
                }
            }
        }
    }
    Ok(response)
}

// This single macro replaces ALL of the manual boilerplate from no-instrumentation-demo:
// - Generates #[tokio::main] async fn main()
// - Initializes OTel tracer provider with X-Ray exporter and environment resource detection
// - Sets up tracing-subscriber with JSON console layer + OTel bridge layer
// - Loads AWS SDK config, creates an instrumented DynamoDB client with OTel interceptor
// - Wraps the Lambda runtime with the OTel Tower layer (per-invocation spans, context propagation)
// - `trigger = OTelFaasTrigger::PubSub` sets the faas.trigger OTel attribute (this Lambda
//   is triggered by SNS/SQS, not HTTP)
//
// See: https://docs.rs/awssdk-instrumentation/latest/awssdk_instrumentation/macro.make_lambda_runtime.html
awssdk_instrumentation::make_lambda_runtime!(
    handler,
    trigger = OTelFaasTrigger::PubSub,
    dynamodb() -> dynamodb_facade::Client
);
